Logging base
WPO-Foundation/wptagent pull request #525
Opened 2022-06-06 15:41 UTC by sammeboy635

I know this is a big PR but all of this is needed for the actions and logging to work together.  

Logging PR:

- New internal/wptutil.py: which adds logging using the existing logging lib.
- New  --debug argument that enables logs, prevents deletion of work files, bypasses idle check for more consistent performance results, and ran with (--testurl (light, medium, heavy)) will automatically set standard testing URL.
- Logs are now through out the code base
- Actions now runs local (Light, Heavy) test, Prints log timing, Verbose runs to each commit, and compares new functions vs old in devtools_parsing.py.
- vvvvv is a new logging format with colors, so we can see errors easily. It also creates logging/main.log which is great for seeing the code flow and timings throughout.

Please Check out the actions for this PR to see all the new tests we have.

2022-06-06 16:05 UTC, sammeboy635 commented
@pmeenan Feel free to let me know what you think!

2022-06-09 17:05 UTC, pmeenan requested changes
Sorry, quite a few comments but at a high level:
* This mixes logging, testing and some utility functions. Separate PR's for each would be a lot cleaner.
* A readme document the best-practices for when to use each logging level is needed.
* The additional log levels should be given useful names
* Would probably be cleaner as a custom logging module that overrides the default logger and adds the new levels (and takes care of setting up the filtering, etc)
* "wptutil" looks like it does a lot of different things, some of which should be moved and the remainder probably require a different module name and should probably be under a /test directory

2022-06-22 18:59 UTC, sammeboy635 commented on internal/desktop_browser.py
> +        if self.options.debug:
Very valid point. There is a --noidle command-line flag but it only applies to preventing idle when starting up and not on each test run. Do you think this --noidle flag should prevent all idling?

2022-06-22 19:07 UTC, sammeboy635 commented on internal/desktop_browser.py
> +        logging.log(8,"Closing the Browser")
I'm not sure if you saw the log that is printed from this line but it is "2022-06-06 15:45:10.395|MainThread|16734|    4|PERFDEB  | Closing the Browser           |desktop_browser.py|close_browser|317". 
The last three fields are | File | Function | Line. 
I can still be more specific if you saw this already.

2022-06-22 19:10 UTC, sammeboy635 commented on internal/wptutil.py
> +
I agree, thanks for that advice!

2022-06-27 00:16 UTC, closed without merging