Removing IE and legacy edge
WPO-Foundation/wptagent pull request #544
Opened 2022-07-13 14:48 UTC by sammeboy635

Cleaning up IE and Legacy Edge from Wptagent. 

Tested Chrome, Firefox, and Chromium Edge

## Chromium Edge
![Microsoft](https://user-images.githubusercontent.com/33207323/178762735-b98d7312-618b-4859-b082-ae2ddf146c9b.png)

## Chrome
![Chrome](https://user-images.githubusercontent.com/33207323/178762854-d9c7325e-72b6-4d46-a42a-df00180c3398.png)

## Firefox
![firefox](https://user-images.githubusercontent.com/33207323/178762900-c48b6c11-7368-49ae-ad7d-4b0ff4cf2996.png)

@pmeenan Please Review!

2022-07-13 15:14 UTC, pmeenan requested changes
Looks good except for the browser detction where it should also add the detected Chromium-based edge as "Microsoft Edge" and "Edge"

2022-07-13 15:50 UTC, sammeboy635 commented on wptagent.py
>          # Microsoft Edge (Chromium)
`
        # Microsoft Edge (Chromium)

        paths = [program_files, program_files_x86, local_appdata]

        channels = ['Microsoft Edge','Edge', 'Edge Dev']
        for channel in channels:`
Adding them to channels?

2022-07-14 14:33 UTC, sammeboy635 commented on wptagent.py
>          # Microsoft Edge (Chromium)
Thanks for clarifying! I stepped through the code on windows just to make sure it was correct with the adjustments we made and this is what browsers{} gets populated with after. If you would like to see more tests or output please do let me know!
![image](https://user-images.githubusercontent.com/33207323/179006417-5c590d84-9632-4e0f-a257-ef20ee5d909c.png)

2022-07-14 14:46 UTC, pmeenan requested changes
One last fix and then I think we're there (beta wouldn't populate correctly without the fix).

2022-07-14 14:46 UTC, pmeenan commented on wptagent.py
> +                        browsers['Microsoft Edge'] = {'exe': edge_path}
This should be `browsers[browser_name] = `

2022-07-14 14:46 UTC, pmeenan commented on wptagent.py
> +                        browsers['Edge'] = {'exe': edge_path}
Same. This should be `browsers[browser_name] = `

2022-07-14 15:58 UTC, pmeenan approved these changes
LGTM.  @tkadlec - before merging, ping me for a few contacts you may want to ping before removing the legacy support as they may be using it in private instances.

2023-01-25 20:05 UTC, closed without merging